### ISSUE TITLE
Toughness and heal power swapped in parsing

### ISSUE THREAD

**Issue by hittingray** [phoenix-oosd/EVTC-Log-Parser#1]
In the parsing for toughness and heal, the numbers have been swapped. Take for example a character with 1500 toughness and 1200 heal power for example. This will show up as 2200 toughness and 1500 heal power instead.

This can be see in Parse.java between lines 74 and 78:

```			
                        // 4 bytes: toughness
			int healing = f.getInt();

			// 4 bytes: healing
			int toughness = f.getInt() + 1000;
```

**Comment by phoenix-oosd** [comment]
Should be fixed now, thanks for the notice. Oddly the comments were correct so I must've not been paying attention when re-writing that.
