### ISSUE TITLE
Update Arc Logs unable to be parsed

### ISSUE THREAD

**Issue by merforga** [phoenix-oosd/EVTC-Log-Parser#2]
Example logs attached with latest Arc Update

[20170207.zip](https://github.com/phoenix-oosd/EVTC-Log-Parser/files/757613/20170207.zip)

**Comment by phoenix-oosd** [comment]
Thanks for the heads up, just fixed it I think.
I hope to release a proper update a while after the patch this week, but I just replaced the .jar file in the release page for now.
I'll leave this issue open, let me know if it works now (1.0.2 .jar).

**Comment by phoenix-oosd** [comment]
Thanks for the heads up, just fixed it I think.
I hope to release a proper update a while after the patch this week, but I just replaced the .jar file in the release page for now.
I'll leave this issue open, let me know if it works now (1.0.2 .jar).
